version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: my-project
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    build: api/
    ports:
      - 3000:3000
    environment:
      - PORT=3000

volumes:
  data:
